# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hb4wyU71pRDlZAs7YGkh4Q9ufbiyJzwZ
"""

# Importar Flask
from flask import Flask, request, jsonify

# Crear una instancia de Flask
app = Flask(__name__)

# Definir una ruta para la API que acepte POST
@app.route('/saludo', methods=['POST'])
def saludo():
    # Obtener el nombre del cuerpo de la solicitud (request body)
    data = request.get_json()
    nombre = data.get('nombre', 'Mundo')
    # Crear una respuesta de saludo
    respuesta = {'mensaje': f'¡Hola, {nombre}!'}
    # Devolver la respuesta en formato JSON
    return jsonify(respuesta)

# Ejecutar la aplicación
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)